# Generated by Django 3.0.2 on 2020-02-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
