# Generated by Django 3.0.2 on 2020-02-26 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200226_1141'),
        ('categories', '0006_auto_20200225_1745'),
        ('quizzes', '0002_quiz_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=16)),
                ('name', models.CharField(max_length=16)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='quiz_categories', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quiz_questions', to='questions.Question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='tags',
            field=models.ManyToManyField(to='quizzes.QuizTag'),
        ),
    ]
