# Generated by Django 3.0.2 on 2020-02-27 17:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20200225_1745'),
        ('questions', '0006_auto_20200226_1141'),
        ('quizzes', '0003_auto_20200226_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='tags',
            field=models.ManyToManyField(blank=True, to='quizzes.QuizTag'),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizCategory')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz')),
            ],
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz'),
        ),
    ]
