# Generated by Django 3.0.2 on 2020-03-01 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_auto_20200228_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcategory',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_categories', to='quizzes.Quiz'),
        ),
    ]
