

export const categoryTypes = {
    CREATE_CATEGORY_START: "CREATE_CATEGORY_START",
    CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
    CREATE_CATEGORY_ERROR: "CREATE_CATEGORY_ERROR",

    FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
    FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
    FETCH_CATEGORIES_ERROR: "FETCH_CATEGORIES_ERROR",

    FETCH_USER_CATEGORIES_START: "FETCH_USER_CATEGORIES_START",
    FETCH_USER_CATEGORIES_SUCCESS: "FETCH_USER_CATEGORIES_SUCCESS",
    FETCH_USER_CATEGORIES_ERROR: "FETCH_USER_CATEGORIES_ERROR",


    CATEGORY_FAVORITE_START: "CATEGORY_FAVORITE_START",
    CATEGORY_FAVORITE_SUCCESS: "CATEGORY_FAVORITE_SUCCESS",
    CATEGORY_UNFAVORITE_SUCCESS: "CATEGORY_UNFAVORITE_SUCCESS",
    CATEGORY_FAVORITE_ERROR: "CATEGORY_FAVORITE_ERROR",

 
}


export default categoryTypes