

const questionTypes = {


    // create question
    CREATE_QUESTION_START: "CREATE_QUESTION_START",
    CREATE_QUESTION_SUCCESS: "CREATE_QUESTION_SUCCESS",
    CREATE_QUESTION_ERROR: "CREATE_QUESTION_ERROR",

    // delete question
    DELETE_QUESTION_START: "DELETE_QUESTION_START",
    DELETE_QUESTION_SUCCESS: "DELETE_QUESTION_SUCCESS",
    DELETE_QUESTION_ERROR: "DELETE_QUESTION_ERROR",

    // fetch categories
    FETCH_QUESTIONS_START: "FETCH_QUESTIONS_START",
    FETCH_QUESTIONS_SUCCESS: "FETCH_QUESTIONS_SUCCESS",
    FETCH_QUESTIONS_ERROR: "FETCH_QUESTIONS_ERROR",

    FAVORITE_QUESTION_START: "FAVORITE_QUESTION_START",
    FAVORITE_QUESTION_SUCCESS: "FAVORITE_QUESTION_SUCCESS",
    UNFAVORITE_QUESTION_SUCCESS: "UNFAVORITE_QUESTION_SUCCESS",
    FAVORITE_QUESTION_ERROR: "FAVORITE_QUESTION_ERROR",
}

export default questionTypes