

const questionTypes = {


    // create categories
    CREATE_QUESTION_START: "CREATE_QUESTION_START",
    CREATE_QUESTION_SUCCESS: "CREATE_QUESTION_SUCCESS",
    CREATE_QUESTION_ERROR: "CREATE_QUESTION_ERROR",

    // fetch categories
    FETCH_QUESTIONS_START: "FETCH_QUESTIONS_START",
    FETCH_QUESTIONS_SUCCESS: "FETCH_QUESTIONS_SUCCESS",
    FETCH_QUESTIONS_ERROR: "FETCH_QUESTIONS_ERROR",
}

export default questionTypes