# Generated by Django 3.0.2 on 2020-02-19 16:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0002_usercategoryfavorites'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercategoryfavorites',
            unique_together={('user', 'category')},
        ),
    ]
