# Generated by Django 3.0.2 on 2020-02-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20200219_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='favorited',
        ),
    ]
