# Generated by Django 3.0.2 on 2020-02-25 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20200225_1745'),
        ('questions', '0004_auto_20200225_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Category'),
        ),
    ]
