const quizTypes = {
    CREATE_QUIZ_START: "CREATE_QUIZ_START",
    CREATE_QUIZ_SUCCESS: "CREATE_QUIZ_SUCCESS",
    CREATE_QUIZ_ERROR: "CREATE_QUIZ_ERROR",

    SET_QUIZ_STATUS_EDIT_QUESTIONS: "SET_QUIZ_STATUS_EDIT_QUESTIONS",
    SET_QUIZ_STATUS_EDIT_BASE_INFO: "SET_QUIZ_STATUS_EDIT_BASE_INFO",

    FETCH_QUIZ_START: "FETCH_QUIZ_START",
    FETCH_QUIZ_SUCCESS: "FETCH_QUIZ_SUCCESS",
    FETCH_QUIZ_ERROR: "FETCH_QUIZ_ERROR"
}

export const quizStatus = {
    EDIT_BASE_INFO: "EDIT_BASE_INFO",
    EDIT_QUESTIONS: "EDIT_QUESTIONS"
}

export default quizTypes